language: php
php:
  - 7.1.3
env:
  - LARAVEL_VERSION=5.6.*
before_script:
  - composer update
  - ln -s storage/app/public public/storage
  - cp .env.travis .env
  - php artisan key:generate
matrix:
  - fast_finish
script:
  - vendor/bin/phpunit
deploy:
  provider: heroku
  api_key:
    - secure: "341d3377-f2dc-43c4-9625-7e9b633e85c7"
  app: theline-heroku
  on:
    repo: LonelyTomb/theLine
